org.gradle.jvmargs=-Xmx1G
minecraft_version=1.21.1
neo_version=21.1.12

parchment_mapping_version=2024.07.28
parchment_mc_version=1.21

mod_version=1.0.0
maven_group=io.github.toolsjs
archives_base_name=toolsjs
mod_id=toolsjs
mod_name=ToolsJS
mod_author=FooterMan,Bluemethyst

kjs_ver=2101.7.0-build.131
kff_ver=5.4.0
gutils_ver=2.1.1-21.0