modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"


issueTrackerURL="https://github.com/FooterManDev/ToolsJS"

[[mods]]
modId = "toolsjs"
version = "${version}"
displayName = "Toolsjs"
logoFile="icon.png"
# credits="Thanks to FooterMan for the KubeJS Addon Template!"
authors="FooterMan,Bluemethyst"
description = '''
A KubeJS addon for custom Tools.
'''

[[dependencies.toolsjs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolsjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolsjs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
